name: CI - Smoke Tests and Migrations

on:
  push:
    branches: [ main, develop, 'feat/**' ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test-migrations:
    name: Test Database Migrations
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: felix_hub_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Cache pip packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Set environment variables
        run: |
          echo "DATABASE_URL=postgresql://postgres:postgres@localhost:5432/felix_hub_test" >> $GITHUB_ENV
          echo "SECRET_KEY=test-secret-key-for-ci" >> $GITHUB_ENV
          echo "ENABLE_CAR_NUMBER=true" >> $GITHUB_ENV
          echo "ALLOW_ANY_CAR_NUMBER=false" >> $GITHUB_ENV
      
      - name: Initialize database
        run: |
          cd felix_hub/backend
          python init_db.py
      
      - name: Test migrations - Apply
        run: |
          cd felix_hub/backend/migrations
          python run_migrations.py apply
      
      - name: Test migrations - Status
        run: |
          cd felix_hub/backend/migrations
          python run_migrations.py status
      
      - name: Test migrations - Rollback
        run: |
          cd felix_hub/backend/migrations
          python run_migrations.py rollback
      
      - name: Test migrations - Re-apply
        run: |
          cd felix_hub/backend/migrations
          python run_migrations.py apply

  api-tests:
    name: API Contract Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Cache pip packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Set environment variables
        run: |
          echo "ENABLE_CAR_NUMBER=true" >> $GITHUB_ENV
          echo "SECRET_KEY=test-secret-key-for-ci" >> $GITHUB_ENV
      
      - name: Run Order API tests
        run: |
          python tests/api/test_orders_api.py
      
      - name: Run Categories API tests
        run: |
          python tests/api/test_categories_api.py
      
      - name: Run Custom Parts API tests
        run: |
          python tests/api/test_custom_parts_api.py

  e2e-tests:
    name: E2E Smoke Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Cache pip packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Set environment variables
        run: |
          echo "ENABLE_CAR_NUMBER=true" >> $GITHUB_ENV
          echo "SECRET_KEY=test-secret-key-for-ci" >> $GITHUB_ENV
      
      - name: Run E2E smoke tests
        run: |
          python tests/e2e/test_order_flow_smoke.py

  full-smoke-test:
    name: Full Smoke Test Suite
    runs-on: ubuntu-latest
    needs: [test-migrations, api-tests, e2e-tests]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Cache pip packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Set environment variables
        run: |
          echo "ENABLE_CAR_NUMBER=true" >> $GITHUB_ENV
          echo "SECRET_KEY=test-secret-key-for-ci" >> $GITHUB_ENV
      
      - name: Run all smoke tests
        run: |
          python tests/run_smoke_tests.py
      
      - name: Summary
        if: always()
        run: |
          echo "✅ All smoke tests completed!"
          echo "Migration tests: Passed"
          echo "API tests: Passed"
          echo "E2E tests: Passed"
